server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
  expiration: 86400000 # 24 hours in milliseconds

# File upload
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB

# Logging
logging:
  level:
    com.salesmanager: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8081
    - http://localhost:8083
    - http://10.0.2.2:8081
    - http://10.0.2.2:8083
    - http://192.168.1.27:8083
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Business Configuration
business:
  stock:
    low-threshold: 10
  notifications:
    expiry-warning-days: 7
  reports:
    timezone: UTC
